name: Release tests-runner base image
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-runner-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: tests-runner/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/metalbear-co/ci-tests-runner-build:latest